services:

  postgres:
    image: postgres:18
    environment:
      POSTGRES_DB: icof
      POSTGRES_USER: icof
      POSTGRES_PASSWORD: icof123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U icof -d icof"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
